blank_issues_enabled: false
contact_links:
  - name: 前往提问区
    url: https://github.com/computer-and-virus/SysTunerProgram/discussions/categories/%E6%8F%90%E9%97%AE%E5%8C%BA
    about: 前往提问区进行提问与解答操作
  - name: 前往讨论区
    url: https://github.com/computer-and-virus/SysTunerProgram/discussions/categories/%E8%AE%A8%E8%AE%BA%E5%8C%BA
    about: 前往讨论区进行自由讨论
  - name: 前往新功能投票区
    url: https://github.com/computer-and-virus/SysTunerProgram/discussions/categories/%E6%96%B0%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8
    about: 前往新功能投票区进行投票
  - name: 前往查看程序公告及最新进展
    url: https://github.com/computer-and-virus/SysTunerProgram/discussions/categories/%E7%A8%8B%E5%BA%8F%E5%85%AC%E5%91%8A%E5%8F%8A%E6%9C%80%E6%96%B0%E8%BF%9B%E5%B1%95
    about: 前往查看程序公告及最新进展
