name: "新功能提案"
description: "点击此选项提出你对于程序的期望功能，或提出你对于程序已有功能的期望修改"
labels: ["新功能", "🆕新提交🆕"]
body:
  - type: markdown
    attributes:
      value: |
        ## 新功能提案
        感谢你花时间提供程序的新功能或对已有功能的新修改！请尽可能详细地填写以下信息。

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查项
      description: "请逐个检查下列项目，并勾选确认。"
      options:
        - label: "我已在 [Issues 页面](https://github.com/computer-and-virus/SysTunerProgram/issues) 中搜索，确认了这个新功能/修改从未被提交过。"
          required: true
        - label: "我已查看 [新功能投票页面](https://github.com/computer-and-virus/SysTunerProgram/discussions/categories/%E6%96%B0%E5%8A%9F%E8%83%BD%E6%8A%95%E7%A5%A8)，确认了这个新功能/修改未在投票列表当中。"
          required: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 描述新功能
      description: "请在下方大输入框中详细描述你想添加的功能或对已有功能的新修改具体是怎样的："
      placeholder: "例：我想要添加...功能，具体是..."
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 描述原因
      description: "请在下方大输入框中输入您为什么需要这个功能或修改，这有利于评估是否接受你的新功能或新修改："
      placeholder: |
        例如：
        我需要这个功能/修改来...。很多人都有...的需求，但如果没有这个功能/修改，就不能...了。
    validations:
      required: true
